class Images {
  Images._();

  static const String femaleSvg = 'assets/images/female.svg';
  static const String maleSvg = 'assets/images/male.svg';
  static const String runningIconSvg = 'assets/images/running_icon.svg';
  static const String barbellIconSvg = 'assets/images/barbell_icon.svg';
  static const String bodyWeightIconSvg = 'assets/images/bodyweight_icon.svg';
  static const String starIcon = 'assets/images/star.svg';
  static const String runningMapIcon = 'assets/images/running_map.svg';
  static const String teamIcon = 'assets/images/team.svg';
  static const String heartIcon = 'assets/images/heart.svg';
  static const String dashboardIcon = 'assets/images/dashboard.svg';
  static const String selectedTab = 'assets/images/selected_tab.svg';
  static const String avatar = 'assets/images/avatar.svg';
  static const String idk = 'assets/images/idkWhatItIs.svg';
  static const String twitter = 'assets/images/twitter.svg';
  static const String discord = 'assets/images/discord.svg';
  static const String messageCircle = 'assets/images/message-circle.svg';
  static const String groupTell = 'assets/images/group_tell.svg';
  static const String edit = 'assets/images/edit.svg';
  static const String xMenAvatar = 'assets/images/x-men.jpg';
  static const String logo = 'assets/images/logo.jpg';
  static const String runGroup = 'assets/images/run_group.jpg';
  static const String eyeclosed = 'assets/images/eyeclosed.svg';
  static const String lockon = 'assets/images/lockon.svg';
  static const String mail = 'assets/images/mail.svg';
  static const String user = 'assets/images/user1.svg';
  static const String cardiology = 'assets/images/cardiology.svg';
  static const String chart = 'assets/images/chartvertical.svg';
  static const String navigation = 'assets/images/navigation.svg';
  static const String usersmore = 'assets/images/usersmore.svg';
  static const String runningGreen = 'assets/images/running_green.svg';
  static const String runningBlue = 'assets/images/running_blue.svg';
  static const String bolt = 'assets/images/bolt.svg';
  static const String groupChatGreen = 'assets/images/group_chat_green.svg';
  static const String target = 'assets/images/target.svg';
  static const String crown = 'assets/images/crown.svg';
  static const String userRunningIcon = 'assets/images/user_run_circle.svg';
}
